---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: loki
  namespace: dpf-operator-system
spec:
  instanceSelector:
    matchLabels:
      dashboards: "dpf-grafana"
  datasource:
    name: loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki.dpf-operator-system.svc.cluster.local:3100
    isDefault: false
    jsonData:
      maxLines: 1000
