apiVersion: v1
kind: Secret
metadata:
  name: <WORKER_NAME>-network-config
  namespace: openshift-machine-api
type: Opaque
stringData:
  nmstate: |
    interfaces:
      - name: <INTERFACE>
        type: ethernet
        state: up
        mtu: <NODES_MTU>
        ipv4:
          enabled: true
          dhcp: false
          address:
            - ip: <IPADDR>
              prefix-length: <PL>
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: <GW>
          next-hop-interface: <INTERFACE>
    dns-resolver:
      config:
        server:
          - <DNS_IP>
