---
apiVersion: v1
kind: Secret
metadata:
  name: <WORKER_NAME>-network-data
  namespace: openshift-machine-api
type: Opaque
stringData:
  nmstate: |
    interfaces:
    - name: boot
      type: ethernet
      state: up
      identifier: mac-address
      mac-address: "<BOOT_MAC>"
      mtu: <NODES_MTU>
      ipv4:
        enabled: true
        dhcp: true
