apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: <CATALOG_SOURCE_NAME>
  namespace: openshift-marketplace
spec:
  displayName: <CATALOG_SOURCE_NAME>
  image: <CATALOG_SOURCE_IMAGE>
  priority: -100
  publisher: Red Hat
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 10m
