#!/bin/bash
# post-install.sh - Prepare and apply post-installation manifests to the cluster

# Exit on error and catch pipe failures
set -e
set -o pipefail

# Source common utilities and configuration
source "$(dirname "${BASH_SOURCE[0]}")/utils.sh"
source "$(dirname "${BASH_SOURCE[0]}")/env.sh"
source "$(dirname "${BASH_SOURCE[0]}")/cluster.sh"

# Configuration
MANIFESTS_DIR=${MANIFESTS_DIR:-"manifests"}
POST_INSTALL_DIR="${MANIFESTS_DIR}/post-installation"
COMMON_POST_INSTALL_DIR="${POST_INSTALL_DIR}/common"
HOST_TRUSTED_POST_INSTALL_DIR="${POST_INSTALL_DIR}/host-trusted"
ZERO_TRUST_POST_INSTALL_DIR="${POST_INSTALL_DIR}/zero-trust"
GENERATED_DIR=${GENERATED_DIR:-"$MANIFESTS_DIR/generated"}
GENERATED_POST_INSTALL_DIR="${GENERATED_DIR}/post-install"
GENERATED_ZT_SERVICE_DIR="${GENERATED_DIR}/zero-trust-services"
OBSERVABILITY_DIR="${MANIFESTS_DIR}/observability"

# BFB Configuration with defaults
BFB_URL=${BFB_URL:-"http://10.8.2.236/bfb/rhcos_4.19.0-ec.4_installer_2025-04-23_07-48-42.bfb"}

# CIDR pool for OVN-Kubernetes VTEPs on the high-speed fabric
VTEP_CIDR=${VTEP_CIDR:-"10.0.120.0/22"}

# Ensure directories exist
mkdir -p "${GENERATED_POST_INSTALL_DIR}"
mkdir -p "${GENERATED_ZT_SERVICE_DIR}"

# List of files that need special processing (excluded from direct copy)
HOST_TRUSTED_SPECIAL_FILES=(
    "hbn-ovn-ipam.yaml"
    "dpu-service-nads.yaml"
    "dpuflavor-1500.yaml"
    "dpuflavor-9000.yaml"
    "dpuflavor.yaml"
    "ovn-configuration.yaml"
    "hbn-configuration.yaml"
    "dpu-node-ipam-controller.yaml"
    "dpudeployment.yaml"
    "nodesriovdevicepluginconfig.yaml"
)

function prepare_zero_trust_provisioning_manifests() {
    log [INFO] "Preparing Zero Trust DPUFlavor, BFB, and DPUDeployment manifests..."

    # Do not mix resources generated by a previous host-trusted preparation
    # with the Zero Trust provisioning set.
    find "${GENERATED_POST_INSTALL_DIR}" -maxdepth 1 -type f -name "*.yaml" -delete

    update_file_multi_replace \
        "${ZERO_TRUST_POST_INSTALL_DIR}/dpuflavor.yaml" \
        "${GENERATED_POST_INSTALL_DIR}/dpuflavor.yaml" \
        "<NUM_VFS>" "${NUM_VFS}"

    update_file_multi_replace \
        "${COMMON_POST_INSTALL_DIR}/bfb.yaml" \
        "${GENERATED_POST_INSTALL_DIR}/bfb.yaml" \
        "<BFB_URL>" "${BFB_URL}"

    update_file_multi_replace \
        "${ZERO_TRUST_POST_INSTALL_DIR}/dpudeployment.yaml" \
        "${GENERATED_POST_INSTALL_DIR}/dpudeployment.yaml"

    log [INFO] "Zero Trust provisioning manifests prepared successfully"
}

function prepare_zero_trust_service_manifests() {
    if [ "${DPF_DEPLOYMENT_MODE}" != "zero-trust" ]; then
        log [ERROR] "Zero Trust service manifests require DPF_DEPLOYMENT_MODE=zero-trust"
        return 1
    fi

    log [INFO] "Preparing Zero Trust DPU service manifests..."

    # Keep Zero Trust service outputs isolated from the trusted post-install set.
    find "${GENERATED_ZT_SERVICE_DIR}" -maxdepth 1 -type f -name "*.yaml" -delete

    validate_zero_trust_dpu_serials || return 1

    local dpu_values=""
    local dpu_entry index serial serial_variable vlan1 vlan2 autonomous_system
    while IFS= read -r serial_variable; do
        serial="${!serial_variable:-}"
        [ -n "${serial}" ] || continue

        index="${serial_variable#DPU}"
        index="${index%_SERIAL}"
        index=$((10#${index}))
        vlan1=$((10 + index))
        vlan2=$((20 + index))
        autonomous_system=$((65001 + (index * 100)))

        # Extend the per-DPU mapping shown in the installation manifest:
        # DPU1 -> VLANs 11/21, AS 65101; DPU2 -> VLANs 12/22, AS 65201.
        printf -v dpu_entry \
            '            - hostnamePattern: "dpu-node-%s*"\n              values:\n                vlan1: %d\n                vlan2: %d\n                bgp_autonomous_system: %d' \
            "${serial}" "${vlan1}" "${vlan2}" "${autonomous_system}"
        if [ -n "${dpu_values}" ]; then
            dpu_values+=$'\n'
        fi
        dpu_values+="${dpu_entry}"
        log [INFO] "Adding ${serial_variable}=${serial} to the Zero Trust HBN configuration"
    done < <(list_dpu_serial_variables)

    local hbn_helm_repo_url="${HBN_HELM_REPO_URL:-https://helm.ngc.nvidia.com/nvidia/doca}"
    local hbn_helm_chart_version="${HBN_HELM_CHART_VERSION:-3.4.0}"
    local hbn_image_repo="${HBN_IMAGE_REPO:-nvcr.io/nvidia/doca/doca_hbn}"
    local hbn_image_tag="${HBN_IMAGE_TAG:-3.4.0-doca3.4.0}"

    update_file_multi_replace \
        "${ZERO_TRUST_POST_INSTALL_DIR}/dpuservicetemplate.yaml" \
        "${GENERATED_ZT_SERVICE_DIR}/dpuservicetemplate-zero-trust.yaml" \
        "<HBN_HELM_REPO_URL>" "${hbn_helm_repo_url}" \
        "<HBN_HELM_CHART_VERSION>" "${hbn_helm_chart_version}" \
        "<HBN_IMAGE_REPO>" "${hbn_image_repo}" \
        "<HBN_IMAGE_TAG>" "${hbn_image_tag}" \
        "<DPU_VALUES>" "${dpu_values}"

    local manifest
    for manifest in \
        dpuserviceinterface \
        dpuserviceipam \
        dpuservicenad; do
        update_file_multi_replace \
            "${ZERO_TRUST_POST_INSTALL_DIR}/${manifest}.yaml" \
            "${GENERATED_ZT_SERVICE_DIR}/${manifest}-zero-trust.yaml"
    done

    update_file_multi_replace \
        "${COMMON_POST_INSTALL_DIR}/dpu-services-scc.yaml" \
        "${GENERATED_ZT_SERVICE_DIR}/dpu-services-scc.yaml"

    log [INFO] "Zero Trust DPU service manifests prepared successfully"
}

function zero_trust_dpudeployment_has_expected_phase() {
    local condition ready_status ready_reason
    condition=$(oc get dpudeployments.svc.dpu.nvidia.com dpudeployment \
        -n dpf-operator-system \
        -o 'jsonpath={.status.conditions[?(@.type=="Ready")].status}{"|"}{.status.conditions[?(@.type=="Ready")].reason}' \
        2>/dev/null || true)
    ready_status="${condition%%|*}"
    ready_reason="${condition#*|}"

    [ "${ready_reason}" = "Pending" ] || [ "${ready_status}" = "True" ]
}

function verify_zero_trust_dpudeployment_created() {
    if ! oc get dpudeployments.svc.dpu.nvidia.com dpudeployment \
        -n dpf-operator-system &>/dev/null; then
        log [ERROR] "Zero Trust DPUDeployment was not created"
        return 1
    fi

    log [INFO] "Waiting for Zero Trust DPUDeployment to reach the expected Pending phase..."
    if ! retry 60 5 zero_trust_dpudeployment_has_expected_phase; then
        log [ERROR] "DPUDeployment did not reach Pending within 5 minutes"
        oc get dpudeployments.svc.dpu.nvidia.com dpudeployment \
            -n dpf-operator-system \
            -o yaml || true
        return 1
    fi

    local ready_status
    ready_status=$(oc get dpudeployments.svc.dpu.nvidia.com dpudeployment \
        -n dpf-operator-system \
        -o 'jsonpath={.status.conditions[?(@.type=="Ready")].status}')
    if [ "${ready_status}" = "True" ]; then
        log [INFO] "Zero Trust DPUDeployment is already Ready (advanced beyond Pending)"
    else
        log [INFO] "Zero Trust DPUDeployment is Pending as expected before DPU service configuration"
    fi
    oc get dpudeployments.svc.dpu.nvidia.com dpudeployment \
        -n dpf-operator-system
}

function dpfhcp_provisioner_is_ready() {
    local phase
    phase=$(oc get dpfhcpprovisioner.provisioning.dpu.hcp.io \
        "${HOSTED_CLUSTER_NAME}" \
        -n "${CLUSTERS_NAMESPACE}" \
        -o jsonpath='{.status.phase}' 2>/dev/null || true)
    [ "${phase}" = "Ready" ]
}

function wait_for_dpfhcp_provisioner_ready() {
    local get_output
    if ! get_output=$(oc get dpfhcpprovisioner.provisioning.dpu.hcp.io \
        "${HOSTED_CLUSTER_NAME}" \
        -n "${CLUSTERS_NAMESPACE}" -o name 2>&1); then
        if ! grep -Eq 'NotFound|not found|doesn.t have a resource type' <<< "${get_output}"; then
            log [ERROR] "Failed to query DPFHCPProvisioner: ${get_output}"
            return 1
        fi
        if [ "${DPF_DEPLOYMENT_MODE}" = "zero-trust" ]; then
            log [ERROR] "DPFHCPProvisioner ${CLUSTERS_NAMESPACE}/${HOSTED_CLUSTER_NAME} was not found"
            return 1
        fi
        log [INFO] "DPFHCPProvisioner is not configured; skipping its readiness check"
        return 0
    fi

    log [INFO] "Waiting for DPFHCPProvisioner to become Ready..."
    if ! retry 180 10 dpfhcp_provisioner_is_ready; then
        log [ERROR] "DPFHCPProvisioner ${HOSTED_CLUSTER_NAME} did not become Ready within 30 minutes"
        oc get dpfhcpprovisioner.provisioning.dpu.hcp.io \
            "${HOSTED_CLUSTER_NAME}" \
            -n "${CLUSTERS_NAMESPACE}" \
            -o yaml || true
        oc get dpucluster.provisioning.dpu.nvidia.com \
            "${HOSTED_CLUSTER_NAME}" \
            -n dpf-operator-system \
            -o yaml || true
        return 1
    fi

    oc get dpfhcpprovisioner.provisioning.dpu.hcp.io \
        "${HOSTED_CLUSTER_NAME}" -n "${CLUSTERS_NAMESPACE}"
}

function apply_zero_trust_provisioning_manifests() {
    local flavor_manifest="${GENERATED_POST_INSTALL_DIR}/dpuflavor.yaml"
    local bfb_manifest="${GENERATED_POST_INSTALL_DIR}/bfb.yaml"
    local deployment_manifest="${GENERATED_POST_INSTALL_DIR}/dpudeployment.yaml"

    for manifest in "${flavor_manifest}" "${bfb_manifest}" "${deployment_manifest}"; do
        if [ ! -f "${manifest}" ]; then
            log [ERROR] "Zero Trust provisioning manifest not found: ${manifest}"
            return 1
        fi
    done

    log [INFO] "Applying Zero Trust DPUFlavor..."
    retry 5 30 apply_manifest "${flavor_manifest}" true

    log [INFO] "Applying Zero Trust BFB..."
    retry 5 30 apply_manifest "${bfb_manifest}" true

    log [INFO] "Waiting for Zero Trust BFB bf-bundle to become Ready..."
    if ! retry 60 10 bash -c \
        'test "$(oc get bfb bf-bundle -n dpf-operator-system -o jsonpath="{.status.phase}" 2>/dev/null)" = Ready'; then
        log [ERROR] "BFB bf-bundle did not become Ready within 10 minutes"
        return 1
    fi

    log [INFO] "Applying Zero Trust DPUDeployment..."
    apply_manifest "${deployment_manifest}" true
    verify_zero_trust_dpudeployment_created
    wait_for_dpfhcp_provisioner_ready

    log [INFO] "Zero Trust DPU provisioning resources applied successfully"
}

function wait_for_zero_trust_service_reconciliation() {
    log [INFO] "Waiting for Zero Trust DPUService applications to reconcile..."
    retry 120 10 oc wait \
        --for=condition=ApplicationsReconciled \
        --timeout=10s \
        --namespace dpf-operator-system \
        dpuservices.svc.dpu.nvidia.com --all

    log [INFO] "Waiting for Zero Trust DPUServiceIPAM resources to reconcile..."
    retry 120 10 oc wait \
        --for=condition=DPUIPAMObjectReconciled \
        --timeout=10s \
        --namespace dpf-operator-system \
        dpuserviceipams.svc.dpu.nvidia.com --all

    log [INFO] "Waiting for Zero Trust DPUServiceInterface resources to reconcile..."
    retry 120 10 oc wait \
        --for=condition=ServiceInterfaceSetReconciled \
        --timeout=10s \
        --namespace dpf-operator-system \
        dpuserviceinterfaces.svc.dpu.nvidia.com --all

    log [INFO] "Waiting for Zero Trust DPUServiceChain resources to reconcile..."
    retry 120 10 oc wait \
        --for=condition=ServiceChainSetReconciled \
        --timeout=10s \
        --namespace dpf-operator-system \
        dpuservicechains.svc.dpu.nvidia.com --all

    oc get dpuservices.svc.dpu.nvidia.com -n dpf-operator-system
    oc get dpuserviceipams.svc.dpu.nvidia.com -n dpf-operator-system
    oc get dpuserviceinterfaces.svc.dpu.nvidia.com -n dpf-operator-system
    oc get dpuservicechains.svc.dpu.nvidia.com -n dpf-operator-system
}

function apply_zero_trust_hosted_cluster_authorization() {
    local rbac_manifest="${GENERATED_ZT_SERVICE_DIR}/dpu-services-scc.yaml"

    if ! ensure_hosted_kubeconfig; then
        log [ERROR] "Hosted-cluster kubeconfig is required for Zero Trust authorization"
        return 1
    fi
    wait_for_hosted_cluster_api "${HOSTED_KUBECONFIG}" 60 10 || return 1

    if [ ! -f "${rbac_manifest}" ]; then
        log [ERROR] "Zero Trust hosted-cluster RBAC manifest not found: ${rbac_manifest}"
        return 1
    fi

    log [INFO] "Applying authorization to the hosted DPU cluster..."
    retry 5 30 oc --kubeconfig="${HOSTED_KUBECONFIG}" apply -f "${rbac_manifest}"

    oc --kubeconfig="${HOSTED_KUBECONFIG}" get clusterrolebinding \
        dpf-system-scc-privileged
}

function print_zero_trust_dpu_provisioning_instructions() {
    local dpu_node dpu_node_names
    local dpu_nodes=()

    if ! dpu_node_names=$(oc get dpunodes.provisioning.dpu.nvidia.com \
        -n dpf-operator-system \
        -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}'); then
        log [WARN] "Unable to read DPUNode names for the manual reboot instructions"
        dpu_node_names=""
    fi

    while IFS= read -r dpu_node; do
        [ -n "${dpu_node}" ] || continue
        dpu_nodes+=("${dpu_node}")
    done <<< "${dpu_node_names}"

    echo ""
    echo "================================================================================"
    echo "DPU provisioning is running - manual action required"
    echo "================================================================================"
    echo "Monitor progress:"
    echo "  oc get dpu -A -w"
    echo ""
    echo "For each DPU that reaches the Rebooting phase:"
    echo "  1. Manually power-cycle the corresponding bare-metal host."
    echo "  2. After the DPU is back up, run from the jump node console:"
    if [ "${#dpu_nodes[@]}" -gt 0 ]; then
        for dpu_node in "${dpu_nodes[@]}"; do
            printf '     oc -n dpf-operator-system annotate dpunode %s \\\n' "${dpu_node}"
            echo "       provisioning.dpu.nvidia.com/dpunode-external-reboot-required-"
        done
    else
        printf '     oc -n dpf-operator-system annotate dpunode <dpunode-name> \\\n'
        echo "       provisioning.dpu.nvidia.com/dpunode-external-reboot-required-"
    fi
    echo "================================================================================"
}

function apply_zero_trust_service_manifests() {
    if [ "${DPF_DEPLOYMENT_MODE}" != "zero-trust" ]; then
        log [ERROR] "Zero Trust DPU services require DPF_DEPLOYMENT_MODE=zero-trust"
        return 1
    fi

    get_kubeconfig

    local manifests=(
        "${GENERATED_ZT_SERVICE_DIR}/dpuservicetemplate-zero-trust.yaml"
        "${GENERATED_ZT_SERVICE_DIR}/dpuserviceinterface-zero-trust.yaml"
        "${GENERATED_ZT_SERVICE_DIR}/dpuservicenad-zero-trust.yaml"
        "${GENERATED_ZT_SERVICE_DIR}/dpuserviceipam-zero-trust.yaml"
    )
    local manifest
    for manifest in "${manifests[@]}"; do
        if [ ! -f "${manifest}" ]; then
            log [ERROR] "Zero Trust service manifest not found: ${manifest}"
            return 1
        fi
        log [INFO] "Applying Zero Trust service manifest: $(basename "${manifest}")"
        retry 5 30 apply_manifest "${manifest}" true
    done

    wait_for_zero_trust_service_reconciliation
    apply_zero_trust_hosted_cluster_authorization
    log [INFO] "Zero Trust DPU services and authorization completed successfully"
    print_zero_trust_dpu_provisioning_instructions
}

# Function to update BFB manifest
function update_bfb_manifest() {
    log [INFO] "Updating BFB manifest..."
    # Update the manifest with custom values using update_file_multi_replace
    update_file_multi_replace \
        "${COMMON_POST_INSTALL_DIR}/bfb.yaml" \
        "${GENERATED_POST_INSTALL_DIR}/bfb.yaml" \
        "<BFB_URL>" "\"${BFB_URL}\""
    log [INFO] "BFB manifest updated successfully"
}

# Function to update HBN OVN manifests
function update_hbn_ovn_manifests() {
    log [INFO] "Updating HBN OVN manifests..."

    # DPU_HOST_CIDR must be set by user
    if [ -z "${DPU_HOST_CIDR}" ]; then
        log [ERROR] "DPU_HOST_CIDR environment variable is not set. Please set it to the DPU nodes subnet (e.g., 10.6.135.0/24)"
        return 1
    fi
    # Update hbn-ovn-ipam.yaml
    update_file_multi_replace \
        "${HOST_TRUSTED_POST_INSTALL_DIR}/hbn-ovn-ipam.yaml" \
        "${GENERATED_POST_INSTALL_DIR}/hbn-ovn-ipam.yaml" \
        "<VTEP_CIDR>" \
        "${VTEP_CIDR}"

    # Update ovn-configuration.yaml for DPUDeployment
    if [ -f "${HOST_TRUSTED_POST_INSTALL_DIR}/ovn-configuration.yaml" ]; then
        # OVN-Kubernetes uses 100 bytes of overhead for Geneve encapsulation.
        local ovn_mtu=$((NODES_MTU - 100))

        log "INFO" "ovn-configuration will be set with MTU:$ovn_mtu"
        update_file_multi_replace \
            "${HOST_TRUSTED_POST_INSTALL_DIR}/ovn-configuration.yaml" \
            "${GENERATED_POST_INSTALL_DIR}/ovn-configuration.yaml" \
            "<VTEP_CIDR>" "${VTEP_CIDR}" \
            "<HOST_CLUSTER_API>" "${HOST_CLUSTER_API}" \
            "<DPU_HOST_CIDR>" "${DPU_HOST_CIDR}" \
            "<NODES_MTU>" "${ovn_mtu}"
    fi

    # Update hbn-configuration.yaml
    if [ -f "${HOST_TRUSTED_POST_INSTALL_DIR}/hbn-configuration.yaml" ]; then
        update_file_multi_replace \
            "${HOST_TRUSTED_POST_INSTALL_DIR}/hbn-configuration.yaml" \
            "${GENERATED_POST_INSTALL_DIR}/hbn-configuration.yaml"
    fi

    log [INFO] "HBN OVN manifests updated successfully"
}

# Function to update VF configuration
function update_vf_configuration() {
    log [INFO] "Updating VF configuration in manifests..."

    # Calculate VF range upper bound
    local vf_range_upper=$((NUM_VFS - 1))

    if [ "$NODES_MTU" == "1500" ]; then
        mtu_source_file="dpuflavor-1500.yaml"
    else
        mtu_source_file="dpuflavor-9000.yaml"
    fi

    log "INFO" "Creating unified dpuflavor.yaml from $mtu_source_file for MTU $NODES_MTU"

    # Copy and process the appropriate source file as dpuflavor.yaml
    update_file_multi_replace \
        "${HOST_TRUSTED_POST_INSTALL_DIR}/$mtu_source_file" \
        "${GENERATED_POST_INSTALL_DIR}/dpuflavor.yaml" \
        "<NUM_VFS>" "${NUM_VFS}"


    log [INFO] "VF configuration updated successfully"
}

# Function to update service template versions
function generate_dpuservicetemplate_overrides() {
    local major_minor
    major_minor=$(echo "${DPF_VERSION#v}" | cut -d. -f1-2)

    local overrides
    overrides=$(jq -n -f "$(dirname "${BASH_SOURCE[0]}")/dpuservicetemplate-overrides.jq" \
        --arg major_minor "${major_minor}" \
        --arg ovn_chart_url "${OVN_CHART_URL:-}" \
        --arg ovn_chart_version "${OVN_CHART_VERSION:-}" \
        --arg hbn_helm_repo_url "${HBN_HELM_REPO_URL:-}" \
        --arg hbn_helm_chart_version "${HBN_HELM_CHART_VERSION:-}" \
        --arg hbn_image_repo "${HBN_IMAGE_REPO:-}" \
        --arg hbn_image_tag "${HBN_IMAGE_TAG:-}" \
        --arg dts_helm_repo_url "${DTS_HELM_REPO_URL:-}" \
        --arg dts_helm_chart_version "${DTS_HELM_CHART_VERSION:-}" \
        --arg dts_image "${DTS_IMAGE:-}")

    if [[ "${overrides}" == "null" ]]; then
        log [INFO] "No DPUServiceTemplate overrides to apply"
        return
    fi

    log [INFO] "Creating DPUServiceTemplate overrides configmap in namespace ${DPF_HCP_PROVISIONER_OPERATOR_NAMESPACE}"
    oc create configmap dpuservicetemplate-overrides \
        -n "${DPF_HCP_PROVISIONER_OPERATOR_NAMESPACE}" \
        --from-literal=overrides.json="${overrides}" \
        --dry-run=client -o yaml | oc apply -f -
}

function update_ipam_controller() {
    # Update IPAM controller manifest (skip for OCP >= 4.22 where Hypershift handles node CIDR allocation natively)
    if ocp_version_gte "${OPENSHIFT_VERSION}" "4.22"; then
        log [INFO] "OCP ${OPENSHIFT_VERSION} >= 4.22: skipping dpu-node-ipam-controller (node CIDR allocation handled by Hypershift)"
    elif [ -f "${HOST_TRUSTED_POST_INSTALL_DIR}/dpu-node-ipam-controller.yaml" ]; then
        update_file_multi_replace \
            "${HOST_TRUSTED_POST_INSTALL_DIR}/dpu-node-ipam-controller.yaml" \
            "${GENERATED_POST_INSTALL_DIR}/dpu-node-ipam-controller.yaml" \
            "<HOSTED_CONTROL_PLANE_NAMESPACE>" "${HOSTED_CONTROL_PLANE_NAMESPACE}" \
            "<HOSTED_CLUSTER_NAME>" "${HOSTED_CLUSTER_NAME}"
        log [INFO] "Updated dpu-node-ipam-controller.yaml with namespace and cluster name"
    fi
}



function update_dpu_service_nad() {
   local svc_file="dpu-service-nads.yaml"

   if [ -f "${HOST_TRUSTED_POST_INSTALL_DIR}/${svc_file}" ]; then
       update_file_multi_replace \
         "${HOST_TRUSTED_POST_INSTALL_DIR}/${svc_file}" \
         "${GENERATED_POST_INSTALL_DIR}/${svc_file}" \
         "<SVC_MTU>" "${NODES_MTU}"
   fi

   log [INFO] "Updated ${svc_file} with MTU: ${NODES_MTU}"
}

function update_nodesriov_device_plugin_config() {
    local src_dp_config="${HOST_TRUSTED_POST_INSTALL_DIR}/nodesriovdevicepluginconfig.yaml"
    if [ ! -f "${src_dp_config}" ]; then
        log [ERROR] "nodesriovdevicepluginconfig.yaml not found in ${HOST_TRUSTED_POST_INSTALL_DIR}"
        return 1
    fi
    local dst_dp_config="${GENERATED_POST_INSTALL_DIR}/nodesriovdevicepluginconfig.yaml"
    local vf_range_end=$((NUM_VFS - 1))
    local pf1_regular_end="${vf_range_end}"
    local kata_sriov_pool=""
    if [ "${KATA_ENABLED}" = "true" ]; then
        if ! [[ "${KATA_NUM_VFS}" =~ ^[1-9][0-9]*$ ]]; then
            log [ERROR] "KATA_NUM_VFS must be a positive integer when KATA_ENABLED=true"
            return 1
        fi
        if [ "${KATA_NUM_VFS}" -ge "${NUM_VFS}" ]; then
            log [ERROR] "KATA_NUM_VFS (${KATA_NUM_VFS}) must be less than NUM_VFS (${NUM_VFS})"
            return 1
        fi
        local pf1_regular_count=$((NUM_VFS - KATA_NUM_VFS))
        pf1_regular_end=$((pf1_regular_count - 1))
        local kata_vf_start=${pf1_regular_count}
        local kata_vf_end=$((NUM_VFS - 1))
        log [INFO] "KATA_ENABLED=true: PF1 regular VFs 0-${pf1_regular_end}, kata pool ${KATA_SRIOV_DP_CONFIG_NAME} VFs ${kata_vf_start}-${kata_vf_end}"
        # Template already has the list-item indent before <KATA_SRIOV_POOL>.
        kata_sriov_pool="- name: ${KATA_SRIOV_DP_CONFIG_NAME}
      type: vf
      ranges:
        - pfIndex: ${KATA_SRIOV_PF_INDEX}
          start: ${kata_vf_start}
          end: ${kata_vf_end}"
    else
        log [INFO] "KATA_ENABLED=${KATA_ENABLED:-false}: skipping kata VF pool (PF1 uses full 0-${vf_range_end})"
    fi
    update_file_multi_replace \
        "${src_dp_config}" \
        "${dst_dp_config}" \
        "<SRIOV_DP_CONFIG_NAME>" "${SRIOV_DP_CONFIG_NAME}" \
        "<SRIOV_DP_CONFIG_CR_NAME>" "${SRIOV_DP_CONFIG_CR_NAME}" \
        "<SRIOV_DP_MGMT_POOL_NAME>" "${SRIOV_DP_MGMT_POOL_NAME}" \
        "<NUM_VFS_END>" "${vf_range_end}" \
        "<PF1_REGULAR_VF_END>" "${pf1_regular_end}" \
        "<KATA_SRIOV_POOL>" "${kata_sriov_pool}"
}

# Function to prepare post-installation manifests
function prepare_post_installation() {
    log [INFO] "Starting post-installation manifest preparation..."

    # Check if post-installation directory exists
    if [ ! -d "${POST_INSTALL_DIR}" ]; then
        log [ERROR] "Post-installation directory not found: ${POST_INSTALL_DIR}"
        exit 1
    fi
    if [ ! -d "${COMMON_POST_INSTALL_DIR}" ]; then
        log [ERROR] "Common post-installation directory not found: ${COMMON_POST_INSTALL_DIR}"
        return 1
    fi
    if ! [[ "${NUM_VFS}" =~ ^[1-9][0-9]*$ ]]; then
        log [ERROR] "NUM_VFS must be a positive integer"
        return 1
    fi

    if [ "${DPF_DEPLOYMENT_MODE}" = "zero-trust" ]; then
        if [ ! -d "${ZERO_TRUST_POST_INSTALL_DIR}" ]; then
            log [ERROR] "Zero Trust post-installation directory not found: ${ZERO_TRUST_POST_INSTALL_DIR}"
            return 1
        fi
        prepare_zero_trust_provisioning_manifests
        log [INFO] "Post-installation manifest preparation completed successfully"
        return 0
    fi

    if [ ! -d "${HOST_TRUSTED_POST_INSTALL_DIR}" ]; then
        log [ERROR] "Host-trusted post-installation directory not found: ${HOST_TRUSTED_POST_INSTALL_DIR}"
        return 1
    fi

    # Update manifests with custom values
    update_bfb_manifest
    update_hbn_ovn_manifests
    update_vf_configuration
    update_ipam_controller
    update_dpu_service_nad
    if [ "${GENERATE_DPUSERVICETEMPLATE_OVERRIDES}" = "true" ]; then
        generate_dpuservicetemplate_overrides
    else
        log [INFO] "Skipping DPUServiceTemplate overrides (GENERATE_DPUSERVICETEMPLATE_OVERRIDES=${GENERATE_DPUSERVICETEMPLATE_OVERRIDES:-false})"
    fi

    # Process DPUDeployment template
    if [ -f "${HOST_TRUSTED_POST_INSTALL_DIR}/dpudeployment.yaml" ]; then
        update_file_multi_replace \
            "${HOST_TRUSTED_POST_INSTALL_DIR}/dpudeployment.yaml" \
            "${GENERATED_POST_INSTALL_DIR}/dpudeployment.yaml" \
            "<SRIOV_DP_CONFIG_CR_NAME>" "${SRIOV_DP_CONFIG_CR_NAME}"
    fi

    # Process NodeSRIOVDevicePluginConfig template
    update_nodesriov_device_plugin_config

    # Copy remaining manifests using utility function (exclude special files)
    copy_manifests_with_exclusions \
        "${COMMON_POST_INSTALL_DIR}" \
        "${GENERATED_POST_INSTALL_DIR}" \
        "bfb.yaml"
    copy_manifests_with_exclusions \
        "${HOST_TRUSTED_POST_INSTALL_DIR}" \
        "${GENERATED_POST_INSTALL_DIR}" \
        "${HOST_TRUSTED_SPECIAL_FILES[@]}"

    log [INFO] "Post-installation manifest preparation completed successfully"
}

# Function to apply post-installation manifests
function apply_post_installation() {
    log [INFO] "Starting post-installation manifest application..."

    # Check if generated post-installation directory exists
    if [ ! -d "${GENERATED_POST_INSTALL_DIR}" ]; then
        log [ERROR] "Generated post-installation directory not found: ${GENERATED_POST_INSTALL_DIR}"
        log [ERROR] "Please run prepare-dpu-files first"
        exit 1
    fi

    # Get kubeconfig
    get_kubeconfig

    # Wait for DPF provisioning webhook to be ready before applying manifests
    log [INFO] "Waiting for DPF provisioning webhook service to be ready..."
    local webhook_ready=false
    local max_attempts=120
    local attempt=0

    while [ $attempt -lt $max_attempts ] && [ "$webhook_ready" = "false" ]; do
        attempt=$((attempt + 1))

        # Check if webhook endpoints are available
        if oc get endpoints -n dpf-operator-system dpf-provisioning-webhook-service -o jsonpath='{.subsets[*].addresses[*].ip}' 2>/dev/null | grep -q .; then
            log [INFO] "DPF provisioning webhook service is ready"
            webhook_ready=true
        else
            if [ $attempt -eq 1 ]; then
                log [INFO] "Waiting for webhook endpoints to be available..."
            fi
            sleep 5
        fi
    done

    if [ "$webhook_ready" = "false" ]; then
        log [ERROR] "DPF provisioning webhook service not ready after $max_attempts attempts"
        log [ERROR] "This may cause failures when applying DPU manifests that require webhook validation"
        # Check if we should fail or continue based on environment variable
        if [ "${STRICT_WEBHOOK_CHECK:-true}" = "true" ]; then
            return 1
        else
            log [WARN] "STRICT_WEBHOOK_CHECK is disabled, proceeding anyway..."
        fi
    fi

    if [ "${DPF_DEPLOYMENT_MODE}" = "zero-trust" ]; then
        apply_zero_trust_provisioning_manifests
        log [INFO] "Post-installation manifest application completed successfully"
        return 0
    fi

    local hosted_kcfg_rc=0
    ensure_hosted_kubeconfig || hosted_kcfg_rc=$?
    if [[ "$hosted_kcfg_rc" -eq 0 ]]; then
        wait_for_hosted_cluster_api "$HOSTED_KUBECONFIG" || return 1
    elif [[ "$hosted_kcfg_rc" -eq 2 ]]; then
        return 1
    fi

    # Apply each YAML file in the generated post-installation directory
    for file in "${GENERATED_POST_INSTALL_DIR}"/*.yaml; do
        if [ -f "$file" ]; then
            local filename=$(basename "$file")
            # Skip dpudeployment.yaml as it will be applied last
            if [[ "${filename}" != "dpudeployment.yaml" ]]; then
                # Special handling for SCC - must be applied to hosted cluster
                if [[ "${filename}" == "dpu-services-scc.yaml" ]]; then
                    if ! ensure_hosted_kubeconfig; then
                        log [ERROR] "Hosted cluster kubeconfig required to apply ${filename}"
                        return 1
                    fi
                    log [INFO] "Applying SCC to hosted cluster: ${filename}"
                    local saved_kubeconfig="${KUBECONFIG}"
                    export KUBECONFIG="${HOSTED_KUBECONFIG}"
                    retry 5 30  apply_manifest "$file" "true"
                    export KUBECONFIG="${saved_kubeconfig}"
                else
                    log [INFO] "Applying post-installation manifest: ${filename}"
                    retry 5 30  apply_manifest "$file" "true"
                fi
            fi
        fi
    done

    # Apply dpudeployment.yaml last if it exists, with apply_always=true
    if [ -f "${GENERATED_POST_INSTALL_DIR}/dpudeployment.yaml" ]; then
        log [INFO] "Applying dpudeployment.yaml (last manifest)..."
        apply_manifest "${GENERATED_POST_INSTALL_DIR}/dpudeployment.yaml" "true"
        wait_for_dpfhcp_provisioner_ready
    else
        log [WARN] "dpudeployment.yaml not found in ${GENERATED_POST_INSTALL_DIR}"
    fi

    log [INFO] "Post-installation manifest application completed successfully"
}

function apply_observability() {
    log [INFO] "Starting observability manifest application..."

    if [ ! -d "${OBSERVABILITY_DIR}" ]; then
        log [ERROR] "Observability directory not found: ${OBSERVABILITY_DIR}"
        exit 1
    fi

    get_kubeconfig

    log [INFO] "Applying observability operator subscriptions..."
    retry 5 30 apply_manifest "${OBSERVABILITY_DIR}/operators" "true"

    log [INFO] "Waiting for Grafana Operator CSV to reach Succeeded..."
    local attempts=0
    local phase=""
    while [ $attempts -lt 60 ]; do
        phase=$(oc -n openshift-operators get csv \
            -l operators.coreos.com/grafana-operator.openshift-operators= \
            -o jsonpath='{.items[0].status.phase}' 2>/dev/null || true)
        if [ "$phase" = "Succeeded" ]; then
            break
        fi
        attempts=$((attempts+1))
        sleep 10
    done
    if [ "$phase" != "Succeeded" ]; then
        log [ERROR] "Grafana Operator CSV did not reach Succeeded after 10 minutes (last phase: '${phase}')"
        return 1
    fi
    log [INFO] "Grafana Operator CSV is Succeeded"

    log [INFO] "Applying DPF metrics manifests..."
    retry 5 30 apply_manifest "${OBSERVABILITY_DIR}/dpf-metrics" "true"

    # Works around a UWM prometheus-operator namespace-cache race where newly
    # applied PodMonitors in dpf-operator-system aren't rendered into the
    # Prometheus scrape config until the operator is kicked. See WA-005.
    log [INFO] "Restarting UWM prometheus-operator to refresh PodMonitor cache..."
    oc -n openshift-user-workload-monitoring rollout restart deploy/prometheus-operator || true
    oc -n openshift-user-workload-monitoring rollout status deploy/prometheus-operator --timeout=120s || true

    log [INFO] "Applying Grafana manifests..."
    retry 5 30 apply_manifest "${OBSERVABILITY_DIR}/grafana" "true"

    # Native OpenShift console dashboards (Observe -> Dashboards). These are
    # ConfigMaps in openshift-config-managed labeled console.openshift.io/dashboard;
    # they render against platform Thanos/UWM with no Grafana dependency.
    if [ -d "${OBSERVABILITY_DIR}/console-dashboards" ]; then
        log [INFO] "Applying OpenShift console dashboards..."
        retry 5 30 apply_manifest "${OBSERVABILITY_DIR}/console-dashboards" "true"
    fi

    log [INFO] "Observability manifest application completed successfully"
}

function redeploy() {
    log [INFO] "Redeploying DPU..."
    prepare_post_installation

    log [INFO] "Deleting existing manifests..."
    oc delete -f "${GENERATED_POST_INSTALL_DIR}/dpudeployment.yaml" || true
    oc delete -f "${GENERATED_POST_INSTALL_DIR}/bfb.yaml" || true

    # wait till all dpu are removed
    if ! retry 60 5 oc wait --for=delete dpu -A --all; then
        log [ERROR] "Failed to wait for DPU deletion"
        return 1
    fi

    oc delete -f "${GENERATED_POST_INSTALL_DIR}/dpuflavor.yaml" || true

    apply_post_installation

}

# If script is executed directly (not sourced), run the appropriate function
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    if [ $# -lt 1 ]; then
        log [ERROR] "Usage: $0 <prepare|apply|prepare-zt-services|apply-zt-services|redeploy|observability|generate-overrides>"
        exit 1
    fi

    case "$1" in
        prepare)
            prepare_post_installation
            ;;
        apply)
            apply_post_installation
            ;;
        prepare-zt-services)
            prepare_zero_trust_service_manifests
            ;;
        apply-zt-services)
            apply_zero_trust_service_manifests
            ;;
        redeploy)
            redeploy
            ;;
        observability)
            apply_observability
            ;;
        generate-overrides)
            generate_dpuservicetemplate_overrides
            ;;
        *)
            log [ERROR] "Unknown command: $1"
            log [ERROR] "Available commands: prepare, apply, prepare-zt-services, apply-zt-services, redeploy, observability, generate-overrides"
            exit 1
            ;;
    esac
fi
