---
apiVersion: provisioning.dpu.nvidia.com/v1alpha1
kind: BFB
metadata:
  name: bf-bundle
  namespace: dpf-operator-system
spec:
  fileName: <BFB_FILENAME>
  url: <BFB_URL>
  versions:
    atf: 4.15.0-4-g419fbf393
    bsp: 4.15.0.13998
    doca: 3.4.1
    uefi: 4.15.0-19-g37c6f5adb2
